"""Google Calendar, reached over its REST API.

Deliberately not using google-api-python-client. That package pulls a large
dependency tree, and this cron installs its requirements every thirty minutes
to make exactly two calls: freeBusy.query and events.insert. google-auth mints
the token; urllib does the rest.

The service account authenticates as itself, not as Lynette. It reaches a
personal calendar because that calendar has been shared with its client_email
directly -- see CalendarConfig for the steps.

One Google limitation shapes this module: a service account cannot add
attendees to an event without domain-wide delegation. So events are created
with no attendees at all, and the client gets an .ics by email from the agent
instead. ics_for() builds it; the mailbox sends it.
"""

from __future__ import annotations

import json
import urllib.error
import urllib.request
import uuid
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

from .config import CalendarConfig

CALENDAR_API = "https://www.googleapis.com/calendar/v3"
SCOPES = ["https://www.googleapis.com/auth/calendar"]


class CalendarError(RuntimeError):
    """The calendar could not be reached, or refused what was asked of it."""


@dataclass(frozen=True)
class Slot:
    """A candidate or booked appointment, always in UTC internally.

    Kept timezone-aware end to end. The only place a local time appears is in
    what the client reads, which is generated by describe().
    """

    start: datetime
    end: datetime

    def overlaps(self, other_start: datetime, other_end: datetime) -> bool:
        # Touching at the boundary is not an overlap: a call ending at 14:00
        # does not conflict with one starting at 14:00.
        return self.start < other_end and other_start < self.end

    def to_iso(self) -> dict:
        return {"start": self.start.isoformat(), "end": self.end.isoformat()}

    @classmethod
    def from_iso(cls, raw: dict) -> Slot:
        return cls(
            start=datetime.fromisoformat(raw["start"]),
            end=datetime.fromisoformat(raw["end"]),
        )


def _zone(name: str):
    """Resolve a timezone, falling back to UTC rather than crashing.

    A missing tzdata on some runner should degrade the wording of a proposal,
    not stop the agent answering its mail.
    """
    try:
        from zoneinfo import ZoneInfo

        return ZoneInfo(name)
    except Exception:  # noqa: BLE001 - bad name, or no tzdata installed
        return timezone.utc


def describe(slot: Slot, tz_name: str) -> str:
    """How a proposed time is written to a client.

    Always names the zone. The agent has no idea where the client is, and
    "Tuesday at 2pm" with no zone is how meetings get missed.

    The 12-hour clock is assembled by hand rather than with %-I, which is a
    glibc extension that raises on Windows -- and this same function will be
    used by the voice agent on a home box that may not be Linux.
    """
    zone = _zone(tz_name)
    local = slot.start.astimezone(zone)

    hour = local.hour % 12 or 12
    meridiem = "AM" if local.hour < 12 else "PM"
    abbreviation = local.strftime("%Z") or tz_name

    return (
        local.strftime("%A")
        + " " + str(local.day)
        + " " + local.strftime("%B")
        + ", " + str(hour) + ":" + local.strftime("%M")
        + " " + meridiem
        + " " + abbreviation
    )


class Calendar:
    def __init__(self, config: CalendarConfig):
        self.config = config
        self._token: str | None = None
        self._credentials = self._load_credentials()

    def _load_credentials(self):
        try:
            from google.oauth2 import service_account
        except ImportError as error:  # pragma: no cover - dependency missing
            raise CalendarError(
                "google-auth is not installed. Run: pip install -r requirements.txt"
            ) from error

        try:
            info = json.loads(self.config.service_account_json)
        except json.JSONDecodeError as error:
            raise CalendarError(
                "GOOGLE_SERVICE_ACCOUNT_JSON is not valid JSON. Paste the whole "
                "downloaded key file, including the surrounding braces."
            ) from error

        try:
            return service_account.Credentials.from_service_account_info(
                info, scopes=SCOPES
            )
        except Exception as error:  # noqa: BLE001
            raise CalendarError("service account key rejected: " + str(error)) from error

    def _authorised_token(self) -> str:
        from google.auth.transport.requests import Request

        if not self._credentials.valid:
            self._credentials.refresh(Request())
        return self._credentials.token

    def _call(self, method: str, path: str, payload: dict | None = None) -> dict:
        url = CALENDAR_API + path
        body = json.dumps(payload).encode("utf-8") if payload is not None else None
        request = urllib.request.Request(url, data=body, method=method)
        request.add_header("Authorization", "Bearer " + self._authorised_token())
        request.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(request, timeout=30) as response:
                return json.loads(response.read().decode("utf-8") or "{}")
        except urllib.error.HTTPError as error:
            detail = error.read().decode("utf-8", errors="replace")[:400]
            raise CalendarError(
                "Calendar API " + method + " " + path + " failed with "
                + str(error.code) + ": " + detail
            ) from error
        except urllib.error.URLError as error:
            raise CalendarError("could not reach the Calendar API: " + str(error)) from error

    # ------------------------------------------------------------------

    def busy(self, start: datetime, end: datetime) -> list:
        """Every busy interval on the calendar between start and end."""
        result = self._call(
            "POST",
            "/freeBusy",
            {
                "timeMin": start.astimezone(timezone.utc).isoformat(),
                "timeMax": end.astimezone(timezone.utc).isoformat(),
                "items": [{"id": self.config.calendar_id}],
            },
        )
        calendars = result.get("calendars", {})
        entry = calendars.get(self.config.calendar_id, {})

        if entry.get("errors"):
            raise CalendarError(
                "calendar '" + self.config.calendar_id + "' returned "
                + str(entry["errors"])
                + ". The usual cause is that it has not been shared with the "
                "service account's client_email."
            )

        periods = []
        for item in entry.get("busy", []):
            periods.append((
                datetime.fromisoformat(item["start"].replace("Z", "+00:00")),
                datetime.fromisoformat(item["end"].replace("Z", "+00:00")),
            ))
        return periods

    def free_slots(self, *, now: datetime | None = None) -> list:
        """Candidate appointment times, soonest first.

        Availability is whatever the calendar is not already busy with. With
        earliest_hour 0 and latest_hour 24 -- the default -- that means all
        hours, exactly as configured.
        """
        now = now or datetime.now(timezone.utc)
        start = now + timedelta(hours=self.config.min_notice_hours)
        end = now + timedelta(days=self.config.horizon_days)

        busy = self.busy(start, end)
        zone = _zone(self.config.timezone)
        length = timedelta(minutes=self.config.slot_minutes)
        buffered = length + timedelta(minutes=self.config.buffer_minutes)

        slots = []
        # Walk forward on the slot grid, aligned to the hour so offered times
        # are round rather than 14:07.
        cursor = start.astimezone(zone).replace(minute=0, second=0, microsecond=0)
        cursor += timedelta(hours=1)

        while cursor < end.astimezone(zone):
            local_hour = cursor.hour
            in_window = (
                self.config.earliest_hour <= local_hour < self.config.latest_hour
                if self.config.earliest_hour < self.config.latest_hour
                else True
            )
            if in_window:
                candidate = Slot(
                    start=cursor.astimezone(timezone.utc),
                    end=(cursor + length).astimezone(timezone.utc),
                )
                # The buffer is applied by widening what counts as a clash, so
                # a call cannot start the instant another ends.
                padded_start = candidate.start - timedelta(minutes=self.config.buffer_minutes)
                padded_end = candidate.start + buffered
                if not any(
                    padded_start < busy_end and busy_start < padded_end
                    for busy_start, busy_end in busy
                ):
                    slots.append(candidate)
            cursor += timedelta(minutes=self.config.slot_minutes)

        return slots

    def is_free(self, slot: Slot) -> bool:
        """Re-check one slot immediately before booking it.

        The gap between offering a time and a client accepting it can be days,
        and the calendar is shared with a human who books their own life into
        it. This is the check that stops the agent double-booking.
        """
        busy = self.busy(
            slot.start - timedelta(minutes=self.config.buffer_minutes),
            slot.end + timedelta(minutes=self.config.buffer_minutes),
        )
        return not any(slot.overlaps(start, end) for start, end in busy)

    def create_event(
        self,
        *,
        slot: Slot,
        summary: str,
        description: str,
        client_name: str,
        client_email: str,
    ) -> dict:
        """Put the call on the calendar. No attendees -- see the module docstring."""
        payload = {
            "summary": summary,
            "description": (
                description
                + "\n\nBooked automatically by the DataRail email receptionist.\n"
                + "Client: " + (client_name or "unknown") + " <" + client_email + ">\n"
                + "The client was sent an .ics invitation by email; they do not "
                + "appear as an attendee here because a service account cannot "
                + "add one."
            ),
            "start": {"dateTime": slot.start.isoformat(), "timeZone": "UTC"},
            "end": {"dateTime": slot.end.isoformat(), "timeZone": "UTC"},
        }
        return self._call(
            "POST", "/calendars/" + _quote(self.config.calendar_id) + "/events", payload
        )

    def doctor(self) -> dict:
        """Prove the credentials work and the calendar is actually shared."""
        report = {"ok": True, "problems": [], "detail": ""}
        try:
            now = datetime.now(timezone.utc)
            busy = self.busy(now, now + timedelta(days=1))
            free = self.free_slots(now=now)
            report["detail"] = (
                str(len(busy)) + " busy period(s) in the next 24h, "
                + str(len(free)) + " free slot(s) within "
                + str(self.config.horizon_days) + " days"
            )
            if not free:
                report["problems"].append(
                    "no free slots found -- the agent will not be able to offer a time"
                )
        except CalendarError as error:
            report["ok"] = False
            report["problems"].append(str(error))
        return report


def _quote(value: str) -> str:
    import urllib.parse

    return urllib.parse.quote(value, safe="")


def ics_for(
    *,
    slot: Slot,
    summary: str,
    description: str,
    organiser_email: str,
    client_email: str,
    client_name: str,
    tz_name: str,
) -> str:
    """An .ics the client's mail app will offer to add to their calendar.

    METHOD:REQUEST with the client as an ATTENDEE, which is what makes Gmail,
    Outlook and Apple Mail show accept/decline buttons rather than a file to
    download.
    """
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    return "\r\n".join([
        "BEGIN:VCALENDAR",
        "VERSION:2.0",
        "PRODID:-//DataRail//Receptionist//EN",
        "CALSCALE:GREGORIAN",
        "METHOD:REQUEST",
        "BEGIN:VEVENT",
        "UID:" + uuid.uuid4().hex + "@datarail.org",
        "DTSTAMP:" + stamp,
        "DTSTART:" + slot.start.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ"),
        "DTEND:" + slot.end.astimezone(timezone.utc).strftime("%Y%m%dT%H%M%SZ"),
        "SUMMARY:" + _escape(summary),
        "DESCRIPTION:" + _escape(description),
        "ORGANIZER;CN=DataRail:mailto:" + organiser_email,
        "ATTENDEE;CN=" + _escape(client_name or client_email)
        + ";ROLE=REQ-PARTICIPANT;PARTSTAT=NEEDS-ACTION;RSVP=TRUE:mailto:" + client_email,
        "STATUS:CONFIRMED",
        "SEQUENCE:0",
        "BEGIN:VALARM",
        "TRIGGER:-PT15M",
        "ACTION:DISPLAY",
        "DESCRIPTION:DataRail intro call in 15 minutes",
        "END:VALARM",
        "END:VEVENT",
        "END:VCALENDAR",
        "",
    ])


def _escape(text: str) -> str:
    """RFC 5545 text escaping. Unescaped commas silently truncate fields."""
    return (
        (text or "")
        .replace("\\", "\\\\")
        .replace(";", "\\;")
        .replace(",", "\\,")
        .replace("\n", "\\n")
    )
